// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBy1cEe7aObJNrTt2V9v4nyT-OeNnFTU8Y',
    appId: '1:192089773032:web:7d2827a2ab5a8617b38a5d',
    messagingSenderId: '192089773032',
    projectId: 'tagit-app-b4b69',
    authDomain: 'tagit-app-b4b69.firebaseapp.com',
    storageBucket: 'tagit-app-b4b69.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDO0F2vTI52NV92Z8dpJJPb-DyiFshFsGQ',
    appId: '1:192089773032:android:f4df87e72cd965b7b38a5d',
    messagingSenderId: '192089773032',
    projectId: 'tagit-app-b4b69',
    storageBucket: 'tagit-app-b4b69.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBy1cEe7aObJNrTt2V9v4nyT-OeNnFTU8Y',
    appId: '1:192089773032:web:ac66bcd2034fd8efb38a5d',
    messagingSenderId: '192089773032',
    projectId: 'tagit-app-b4b69',
    authDomain: 'tagit-app-b4b69.firebaseapp.com',
    storageBucket: 'tagit-app-b4b69.firebasestorage.app',
  );
}
